version: 2
models:
  - name: silver__asset_config
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - asset_id
    columns:
      - name: ASSET_ID
        tests:
          - not_null
      - name: ASSET_NAME
        tests:
          - not_null
      - name: ASSET_AMOUNT
        tests:
          - not_null
      - name: DECIMALS
        tests:
          - not_null
          