version: 2
models:
  - name: core__ez_transaction_application_call
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - BLOCK_ID
            - INTRA
    columns:
      - name: BLOCK_TIMESTAMP
        description: "{{ doc('block_timestamp') }}"
        tests:
          - not_null
          - dbt_expectations.expect_row_values_to_have_recent_data:
              datepart: day
              interval: 1
      - name: BLOCK_DATE
        tests:
          - not_null
      - name: BLOCK_ID
        tests:
          - not_null
      - name: INTRA
        tests:
          - not_null
      - name: TX_ID
        tests:
          - not_null
      - name: TX_GROUP_ID
      - name: INNER_TX
        tests:
          - not_null
      - name: TX_SENDER
        tests:
          - not_null   
      - name: FEE
        tests:
          - not_null:
              where: inner_tx = 'true'
      - name: APP_ID
        tests:
          - not_null   
      - name: TX_TYPE
        tests:
          - not_null
      - name: TX_TYPE_NAME
        tests:
          - not_null
      - name: TX_MESSAGE
        tests:
          - not_null
      - name: EXTRA
        tests:
          - not_null  
