version: 2
models:
  - name: core__dim_application
    description: ""
    columns:
      - name: DIM_APPLICATION_ID
        description: "{{ doc('sk') }}"
        tests:
          - dbt_expectations.expect_column_to_exist
      - name: APP_ID
        description: "{{ doc('app_id') }}"
        tests:
          - not_null:
              where:  DIM_APPLICATION_ID not in ('-1','-2')   
      - name: PARAMS
        description: "Parameters related to the app"
        tests:
          - dbt_expectations.expect_column_to_exist 
      - name: APP_CLOSED
        description: "Whether or not the app is currently deleted"
        tests:
          - not_null:
              where:  DIM_APPLICATION_ID not in ('-1','-2')
      - name: DIM_ACCOUNT_ID__CREATOR
        description: "FK to DIM_ACCOUNT for the creator address"
        tests:
          - not_null
          - negative_one:
              where: _inserted_timestamp <  (CURRENT_TIMESTAMP - INTERVAL '28 HOURS') and DIM_APPLICATION_ID not in ('-1','-2')
      - name: CREATOR_ADDRESS
        description: "Wallet creator account address"
        tests:
          - not_null:
              where:  DIM_APPLICATION_ID not in ('-1','-2')
      - name: DIM_BLOCK_ID__CREATED_AT
        description: "FK to DIM_BLOCK for the created at datetime"
        tests:
          - not_null   
          - negative_one:
              where: _inserted_timestamp <  (CURRENT_TIMESTAMP - INTERVAL '8 HOURS') and DIM_APPLICATION_ID not in ('-1','-2')
      - name: CREATED_AT
        description: "Block timestamp that the app was created"
        tests:
          - not_null:
              where:  DIM_APPLICATION_ID not in ('-1','-2')
      - name: DIM_BLOCK_ID__CLOSED_AT
        description: "FK to DIM_BLOCK for the closed at datetime"
        tests:
          - not_null   
      - name: CLOSED_AT
        description: "Block timestamp that the app was deleted"
        tests:
          - dbt_expectations.expect_column_to_exist               
    tests:
      - dbt_constraints.primary_key:
          column_name: DIM_APPLICATION_ID
      - dbt_constraints.foreign_key:
          fk_column_name: DIM_ACCOUNT_ID__CREATOR
          pk_table_name: ref('core__dim_account')
          pk_column_name: DIM_ACCOUNT_ID
      - dbt_constraints.foreign_key:
          fk_column_name: DIM_BLOCK_ID__CREATED_AT
          pk_table_name: ref('core__dim_block')
          pk_column_name: DIM_BLOCK_ID
      - dbt_constraints.foreign_key:
          fk_column_name: DIM_BLOCK_ID__CLOSED_AT
          pk_table_name: ref('core__dim_block')
          pk_column_name: DIM_BLOCK_ID


