version: 2
models:
  - name: core__dim_application
    description: ""
    columns:
      - name: DIM_APPLICATION_ID
        description: "ABC "
        tests:
          - dbt_expectations.expect_column_to_exist
    tests:
      - dbt_constraints.primary_key:
          column_name: DIM_APPLICATION_ID
      - dbt_constraints.foreign_key:
          fk_column_name: DIM_ACCOUNT_ID__CREATOR
          pk_table_name: ref('core__dim_account')
          pk_column_name: DIM_ACCOUNT_ID
      - dbt_constraints.foreign_key:
          fk_column_name: DIM_BLOCK_ID__CREATED_AT
          pk_table_name: ref('core__dim_block')
          pk_column_name: DIM_BLOCK_ID
      - dbt_constraints.foreign_key:
          fk_column_name: DIM_BLOCK_ID__CLOSED_AT
          pk_table_name: ref('core__dim_block')
          pk_column_name: DIM_BLOCK_ID


