name: Push File

on: push

jobs:
  pull-request:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Create pull request
      uses: dmnemec/copy_file_to_another_repo_action@main
      env:
        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      with:
        source_file: './.gitub/workflows/manual.yml'
        destination_repo: 'FlipsideCrypto/axelar-models/tests_auto'
        destination_folder: './.gitub/workflows'
        user_email: 'xiuyang@flipsidecrypto.com'
        user_name: 'xiuy001'
        commit_message: 'A custom message for the commit'
