# This is a basic workflow that is manually triggered

name: dbt run ad hoc job

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on: 
  workflow_dispatch:
    inputs:
      dbt_command:
        type: string
        description: 'dbt commands to run'
        required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  greet:
    # The type of runner that the job will run on
    strategy:
      matrix:
        msg: ${{fromJson(inputs.dbt_command)}}
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - name: Send greeting
      run: echo "Hello ${{ matrix.msg }}"