name: dbt_run_ad_hoc_template

on:
  workflow_call:
    inputs:
      dbt_command:
        type: string
        description: 'dbt commands to run'
        required: true

jobs:
  run_dbt_jobs:
    runs-on: ubuntu-latest
    environment: 
      name: workflow
    strategy:
      matrix:
        msg: ${{fromJson(inputs.dbt_command)}}

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v1
        with:
          python-version: "3.7.x"

      - name: install dependencies
        run: |
          pip3 install dbt-snowflake cli_passthrough requests click
          dbt deps

      - name: Run DBT Jobs
        run: |
          ${{ matrix.msg }}

  