# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    inputs:
      dbt_command:
        type: string
        description: 'DBT Run Command'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ${{fromJson(inputs.dbt_command)}}
    steps:
      - name: Send greeting
        run: echo "Hello ${{ matrix.node }}"