version: 2

sources:
  - name: shared
    database: flipside_prod_db
    schema: silver
    tables:
      - name: prices
      - name: prices_v2
      - name: cmc_assets
      - name: market_asset_metadata
      - name: coingecko_prices
      - name: hours
      - name: udm_address_labels
      - name: udm_address_labels_new
      - name: udm_address_tags
      - name: udm_balances
      - name: udm_decimal_adjustments
      - name: udm_velocity
      - name: uniswapv2factory_event_paircreated
      - name: flow_balances
      - name: near_balances
      - name: algorand_balances
      - name: terra_balances
  - name: bronze
    database: flipside_prod_db
    schema: bronze
    tables:
      - name: prod_nft_metadata_uploads_1828572827
  - name: crosschain
    database: flipside_prod_db
    schema: silver_crosschain
    tables:
      - name: address_labels
  - name: algorand
    database: hevo
    schema: BRONZE_ALGORAND_2_8_0__HEVO_PARALLEL
    tables:
      - name: ACCOUNT
      - name: ACCOUNT_APP
      - name: ACCOUNT_ASSET
      - name: APP
      - name: ASSET
      - name: BLOCK_HEADER
      - name: METASTATE
      - name: TXN
      - name: TXN_PARTICIPATION
  - name: prod
    database: chainwalkers
    schema: prod
    tables:
      - name: solana_blocks
      - name: solana_txs
      - name: ethereum_blocks
      - name: ethereum_txs
  - name: algorand_db_external
    database: flipside_prod_db
    schema: bronze
    loader: S3
    tables:
      - name: algorand_indexer_tx
        external:
          location: "@{{ target.database }}.bronze.ANALYTICS_EXTERNAL_TABLES/ALGORAND_INDEXER_{{ target.name }}/TX"
          file_format: "( type = json, strip_outer_array = TRUE )"
          auto_refresh: false
          partitions:
            - name: _partition_by_date
              data_type: date
              expression: to_date(split_part(metadata$filename, '/', 3) || split_part(metadata$filename, '/', 4) || split_part(metadata$filename, '/', 5), 'YYYYMMDD')
        columns:
          - name: account_id
            data_type: string
            description: "account_id used in request"
            expression: value:account_id::string
          - name: tx_id
            data_type: string
            description: "txid used in request"
            expression: value:tx_id::string
          - name: metadata
            data_type: variant
            description: "raw indexer response"
            expression: value:metadata::variant
          - name: data
            data_type: variant
            description: "raw indexer response"
            expression: value:data::variant